/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labtask3;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class updateForm extends javax.swing.JFrame {
    DefaultTableModel model;
    DefaultTableModel model2;
    
    public updateForm() {
        initComponents();
    }
    
    
    int editingRow = -1;
    
    public void setTableModel(DefaultTableModel sharedModel, DefaultTableModel sharedModel2) {
        this.model = sharedModel;
        this.model2 = sharedModel2;
        jTable1.setModel(this.model);
        jTable1.revalidate();
        jTable1.repaint();
    }
    
    public void clearFields() {
        fullNameTextField.setText("");
        maleRButton.setSelected(false);
        femaleRButton.setSelected(false);
        programComboBox.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fullNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        maleRButton = new javax.swing.JRadioButton();
        femaleRButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        programComboBox = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        saveUpdateButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(766, 150));
        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 100));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel2.add(backButton);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Noto Serif KR", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Full Name:");
        jPanel3.add(jLabel4);

        fullNameTextField.setBackground(new java.awt.Color(255, 255, 255));
        fullNameTextField.setPreferredSize(new java.awt.Dimension(200, 29));
        fullNameTextField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                fullNameTextFieldInputMethodTextChanged(evt);
            }
        });
        fullNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameTextFieldActionPerformed(evt);
            }
        });
        fullNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fullNameTextFieldKeyReleased(evt);
            }
        });
        jPanel3.add(fullNameTextField);

        jLabel6.setFont(new java.awt.Font("Noto Serif KR", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Gender:");
        jPanel3.add(jLabel6);

        maleRButton.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(maleRButton);
        maleRButton.setFont(new java.awt.Font("Noto Serif KR", 0, 12)); // NOI18N
        maleRButton.setForeground(new java.awt.Color(0, 0, 0));
        maleRButton.setText("Male");
        jPanel3.add(maleRButton);

        femaleRButton.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(femaleRButton);
        femaleRButton.setFont(new java.awt.Font("Noto Serif KR", 0, 12)); // NOI18N
        femaleRButton.setForeground(new java.awt.Color(0, 0, 0));
        femaleRButton.setText("Female");
        jPanel3.add(femaleRButton);

        jLabel7.setFont(new java.awt.Font("Noto Serif KR", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Program:");
        jPanel3.add(jLabel7);

        programComboBox.setBackground(new java.awt.Color(255, 255, 255));
        programComboBox.setFont(new java.awt.Font("Noto Serif KR", 0, 12)); // NOI18N
        programComboBox.setForeground(new java.awt.Color(0, 0, 0));
        programComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COE", "IT", "CRI", "PSY", "ENG", "ACC", "PS", "MM", "SW", "AMT", "FM", "HR", "SCI" }));
        programComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                programComboBoxMouseClicked(evt);
            }
        });
        programComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programComboBoxActionPerformed(evt);
            }
        });
        jPanel3.add(programComboBox);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));

        saveUpdateButton.setBackground(new java.awt.Color(255, 255, 255));
        saveUpdateButton.setForeground(new java.awt.Color(0, 0, 0));
        saveUpdateButton.setText("Save update");
        saveUpdateButton.setEnabled(false);
        saveUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUpdateButtonActionPerformed(evt);
            }
        });
        jPanel4.add(saveUpdateButton);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Gender", "Program"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(782, 684));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTextFieldActionPerformed

    private void programComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_programComboBoxMouseClicked

    private void programComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programComboBoxActionPerformed

    private void saveUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUpdateButtonActionPerformed
        if (editingRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a student info from the table to update.", "Unknown Info Update", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String radioButton = "";
        
            if (maleRButton.isSelected()) {
                radioButton = "Male";
            }
            else if (femaleRButton.isSelected()) {
                radioButton = "Female";
            }
            else {
                JOptionPane.showMessageDialog(this, "Please input your gender.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        
//            Object[] rowDate = new Object[] {fullNameTextField.getText(), radioButton, programComboBox.getSelectedItem()};
        
            JOptionPane.showMessageDialog(this, "Student info updated successfully.", "Info updated", JOptionPane.INFORMATION_MESSAGE);
            
            if (editingRow >= 0) {
                model.setValueAt(fullNameTextField.getText(), editingRow, 0);
                model2.setValueAt(fullNameTextField.getText(), editingRow, 0);
                model.setValueAt(radioButton, editingRow, 1);
                model2.setValueAt(radioButton, editingRow, 1);
                model.setValueAt(programComboBox.getSelectedItem(), editingRow, 2);
                model2.setValueAt(programComboBox.getSelectedItem(), editingRow, 2);
                editingRow = -1;
            }
            else {
                JOptionPane.showMessageDialog(this, "Please select a row to update.");
            }
            clearFields();
            if (fullNameTextField.getText().isEmpty()) {
                saveUpdateButton.setEnabled(false);
            }
            else {
                saveUpdateButton.setEnabled(true);
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Unknown error has been occured.", "Unknown Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveUpdateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed
 
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            try {
                editingRow = selectedRow;
                Object fullName = model.getValueAt(selectedRow, 0);
                fullNameTextField.setText(fullName != null ? fullName.toString() : "");
                String gender = model.getValueAt(selectedRow, 1) != null ? model.getValueAt(selectedRow, 1).toString() : "";
                if (gender.equalsIgnoreCase("Male")) {
                    maleRButton.setSelected(true);
                }
                else if (gender.equalsIgnoreCase("Female")) {
                    femaleRButton.setSelected(true);
                }
                String program = model.getValueAt(selectedRow, 2) != null ? model.getValueAt(selectedRow, 2).toString() : "";
                programComboBox.setSelectedItem(program);
                saveUpdateButton.setEnabled(true);
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Unknown error has been occured. Please try again.", "Unknown Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void fullNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fullNameTextFieldKeyReleased
        
        if (fullNameTextField.getText().isBlank()) {
            saveUpdateButton.setEnabled(false);
        }
        else {
            saveUpdateButton.setEnabled(true);
        }
    }//GEN-LAST:event_fullNameTextFieldKeyReleased

    private void fullNameTextFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fullNameTextFieldInputMethodTextChanged
        
    }//GEN-LAST:event_fullNameTextFieldInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton femaleRButton;
    private javax.swing.JTextField fullNameTextField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JRadioButton maleRButton;
    private javax.swing.JComboBox<String> programComboBox;
    private javax.swing.JButton saveUpdateButton;
    // End of variables declaration//GEN-END:variables
}
