/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spa;

import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class labtask1 extends javax.swing.JFrame {

    /**
     * Creates new form information
     */
    public labtask1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Firstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Middlename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Lastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Suffix = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Street = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Block = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Barangay = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Municipality = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Province = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Country = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 740));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setEnabled(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 105));

        jLabel15.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Popula");

        jLabel16.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("GLORY TO UM Census");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(175, 175, 175))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1);

        Firstname.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(Firstname);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Middle  Name");
        jLabel2.setPreferredSize(new java.awt.Dimension(85, 15));
        jPanel1.add(jLabel2);

        Middlename.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(Middlename);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Last Name ");
        jPanel1.add(jLabel3);

        Lastname.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(Lastname);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Suffix:");
        jPanel1.add(jLabel4);

        Suffix.setMinimumSize(new java.awt.Dimension(250, 22));
        Suffix.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(Suffix);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Age:");
        jPanel1.add(jLabel5);

        Age.setPreferredSize(new java.awt.Dimension(64, 25));
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        Age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AgeKeyTyped(evt);
            }
        });
        jPanel1.add(Age);

        jLabel18.setText("                                                                           ");
        jPanel1.add(jLabel18);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Home Address");
        jPanel1.add(jLabel7);

        jLabel14.setText("                                                           ");
        jPanel1.add(jLabel14);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Street");
        jPanel1.add(jLabel8);

        Street.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(Street);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Block");
        jPanel1.add(jLabel9);

        Block.setMinimumSize(new java.awt.Dimension(250, 25));
        Block.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(Block);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Barangay");
        jPanel1.add(jLabel10);

        Barangay.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(Barangay);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Municipality/City");
        jPanel1.add(jLabel11);

        Municipality.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(Municipality);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Province");
        jPanel1.add(jLabel12);

        Province.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(Province);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Country");
        jPanel1.add(jLabel13);

        Country.setMinimumSize(new java.awt.Dimension(250, 25));
        Country.setPreferredSize(new java.awt.Dimension(250, 25));
        jPanel1.add(Country);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jPanel3.add(jPanel1);

        getContentPane().add(jPanel3);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String firstName = Firstname.getText().trim();
        String middleName = Middlename.getText().trim();
        String lastName = Lastname.getText().trim();
        String suffix = Suffix.getText();
        String AGE = Age.getText().trim();
        String street = Street.getText().trim();
        String block = Block.getText();
        String barangay = Barangay.getText().trim();
        String municipalityORcity = Municipality.getText().trim();
        String province = Province.getText().trim();
        String country = Country.getText().trim();
        
        if (firstName.isEmpty() && middleName.isEmpty() && lastName.isEmpty() && suffix.isEmpty() && AGE.isEmpty()
                && street.isEmpty() && block.isEmpty() && barangay.isEmpty() && municipalityORcity.isEmpty() && province.isEmpty() && country.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Input all information.", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        }
        else {
            Icon icon = new javax.swing.ImageIcon(getClass().getResource("/spa/labyu.png"));
            JOptionPane.showMessageDialog(this, "Information saved!", "Added Successfully", JOptionPane.INFORMATION_MESSAGE, icon);
        }
        try {
            int age = Integer.parseInt(AGE);
        }
        catch (NumberFormatException e) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void AgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeKeyTyped
        char type = evt.getKeyChar();
        
        if (!Character.isDigit(type)) {
            evt.consume();
        }
    }//GEN-LAST:event_AgeKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Firstname.setText("");
        Middlename.setText("");
        Lastname.setText("");
        Suffix.setText("");
        Age.setText("");
        Street.setText("");
        Block.setText("");
        Barangay.setText("");
        Municipality.setText("");
        Province.setText("");
        Country.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Icon icon = new javax.swing.ImageIcon(getClass().getResource("/spa/labyu.png"));
        JOptionPane.showMessageDialog(this, "Information deleted successfullly!", "Deletion Successfully", JOptionPane.INFORMATION_MESSAGE, icon);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(labtask1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(labtask1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(labtask1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(labtask1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new labtask1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Barangay;
    private javax.swing.JTextField Block;
    private javax.swing.JTextField Country;
    private javax.swing.JTextField Firstname;
    private javax.swing.JTextField Lastname;
    private javax.swing.JTextField Middlename;
    private javax.swing.JTextField Municipality;
    private javax.swing.JTextField Province;
    private javax.swing.JTextField Street;
    private javax.swing.JTextField Suffix;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
