/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeemanagement;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        jTable1.setModel(model);
    }
    
    DefaultTableModel model =  new DefaultTableModel(new Object[] {"First Name", "Middle Name", "Last Name", "Age", "Gender", "Language", "Birth Date"}, 0);
    int editingRow = -1;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(956, 130));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Noto Serif KR", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(58, 5, 25));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GMALL EMPLOYEE PROFILE FORM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 69, 0, 111);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employeemanagement/gmall.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 67, 16, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(420, 599));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Noto Serif KR", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(58, 5, 25));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 6, 0, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Noto Serif KR", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 145;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 11, 0, 14);
        jPanel2.add(jTextField1, gridBagConstraints);

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Noto Serif KR", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 145;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 11, 0, 14);
        jPanel2.add(jTextField2, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Noto Serif KR", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(58, 5, 25));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Middle Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 6, 0, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Noto Serif KR", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(58, 5, 25));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel2.add(jLabel7, gridBagConstraints);

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Noto Serif KR", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 145;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 11, 0, 14);
        jPanel2.add(jTextField3, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100+" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 6, 0, 0);
        jPanel2.add(jComboBox1, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Noto Serif KR", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(58, 5, 25));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Age:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 6, 0, 0);
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Noto Serif KR", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(58, 5, 25));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Language:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 28;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 18, 0, 0);
        jPanel2.add(jLabel9, gridBagConstraints);

        jCheckBox1.setFont(new java.awt.Font("Noto Serif KR", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(58, 5, 25));
        jCheckBox1.setText("English");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 67;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 42;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 6, 0, 0);
        jPanel2.add(jCheckBox1, gridBagConstraints);

        jCheckBox2.setFont(new java.awt.Font("Noto Serif KR", 0, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(58, 5, 25));
        jCheckBox2.setText("Bisaya");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 67;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel2.add(jCheckBox2, gridBagConstraints);

        jCheckBox3.setFont(new java.awt.Font("Noto Serif KR", 0, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(58, 5, 25));
        jCheckBox3.setText("Tagalog");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 67;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 63;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel2.add(jCheckBox3, gridBagConstraints);

        jDateChooser1.setDateFormatString("MMMM dd, yyyy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 143;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 1, 0, 0);
        jPanel2.add(jDateChooser1, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Noto Serif KR", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(58, 5, 25));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Birth Date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 30, 0, 0);
        jPanel2.add(jLabel10, gridBagConstraints);

        jRadioButton2.setFont(new java.awt.Font("Noto Serif KR", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(58, 5, 25));
        jRadioButton2.setText("Female");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel2.add(jRadioButton2, gridBagConstraints);

        jRadioButton1.setFont(new java.awt.Font("Noto Serif KR", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(58, 5, 25));
        jRadioButton1.setText("Male");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 6, 0, 0);
        jPanel2.add(jRadioButton1, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Noto Serif KR", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(58, 5, 25));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Gender:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel2.add(jLabel11, gridBagConstraints);

        saveButton.setBackground(new java.awt.Color(255, 51, 51));
        saveButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(63, 30, 85, 0);
        jPanel2.add(saveButton, gridBagConstraints);

        deleteButton.setBackground(new java.awt.Color(255, 51, 51));
        deleteButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(63, 1, 85, 0);
        jPanel2.add(deleteButton, gridBagConstraints);

        updateButton.setBackground(new java.awt.Color(255, 51, 51));
        updateButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 47;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(63, 18, 85, 0);
        jPanel2.add(updateButton, gridBagConstraints);

        printButton.setBackground(new java.awt.Color(255, 51, 51));
        printButton.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        printButton.setForeground(new java.awt.Color(255, 255, 255));
        printButton.setText("Print");
        printButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 88;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(63, 18, 85, 0);
        jPanel2.add(printButton, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Middle Name", "Last Name", "Age", "Gender", "Language", "Birth Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void clearFormFields() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedIndex(0);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jDateChooser1.setDate(null);
    }
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            String radioB = "";
            String language;
            String date = "";
            StringBuilder sb = new StringBuilder();
            JCheckBox[] check = {jCheckBox1, jCheckBox2, jCheckBox3};
        
            for (JCheckBox jcheckbox : check) {
                if (jcheckbox.isSelected()) {
                    sb.append(jcheckbox.getText()).append("\n");
                }
            }
        
            model = (DefaultTableModel) jTable1.getModel();
            jTable1.setModel(model);
            Date selectedDate = jDateChooser1.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
            String formattedDate = sdf.format(selectedDate);
            date = formattedDate;
            if (selectedDate.equals(null)) {
                JOptionPane.showMessageDialog(this, "Please input birthdate.");
                return;
            }
        
            if (jRadioButton1.isSelected()) {
                radioB = "Male";
            }
            else if (jRadioButton2.isSelected()) {
                radioB = "Female";
            }
        
            language = sb.toString();
        
            Object[] rowData = new Object[] {jTextField1.getText(), jTextField2.getText(), jTextField3.getText(), jComboBox1.getSelectedItem(), radioB, language, date};
        
            if (editingRow >= 0) {
            
                model.setValueAt(jTextField1.getText(), editingRow, 0);
                model.setValueAt(jTextField2.getText(), editingRow, 1);
                model.setValueAt(jTextField3.getText(), editingRow, 2);
                model.setValueAt(jComboBox1.getSelectedItem(), editingRow, 3);
                model.setValueAt(radioB, editingRow, 4);
                model.setValueAt(language, editingRow, 5);
                model.setValueAt(date, editingRow, 6);
                editingRow = -1;
            }
            else {
                model.addRow(new Object[] {jTextField1.getText(), jTextField2.getText(), jTextField3.getText(), jComboBox1.getSelectedItem(), radioB, language, date});
            }
            clearFormFields();
            JOptionPane.showMessageDialog(this, "Info added successfully.", "Info added", JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please fill up the fields.", "Fill up error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        model = (DefaultTableModel) jTable1.getModel();
        
        if (jTable1.getSelectedRowCount() == 1) {

              int con = JOptionPane.showConfirmDialog(this, "Do you want to delete this?");
              if (con == 0) {
                  model.removeRow(jTable1.getSelectedRow());
                  JOptionPane.showMessageDialog(this, "Info deleted.");
              }
              else if (con == 1) {
                  JOptionPane.showMessageDialog(this, "Okay.");
              }
        }
        else {
            if (jTable1.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Info is empty.", "Emtpy", JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, "Please select a data to delete.", "No data selection", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String radioB = "";
        String language;
        String date = "";
        StringBuilder sb = new StringBuilder();
        JCheckBox[] check = {jCheckBox1, jCheckBox2, jCheckBox3};
        
        for (JCheckBox jcheckbox : check) {
            if (jcheckbox.isSelected()) {
                sb.append(jcheckbox.getText()).append("\n");
            }
        }
        
        model = (DefaultTableModel) jTable1.getModel();
        jTable1.setModel(model);
        Date selectedDate = jDateChooser1.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        String formattedDate = sdf.format(selectedDate);
        date = formattedDate;
        if (selectedDate.equals(null)) {
            JOptionPane.showMessageDialog(this, "Please input birthdate.");
            return;
        }
        
        if (jRadioButton1.isSelected()) {
            radioB = "Male";
        }
        else if (jRadioButton2.isSelected()) {
            radioB = "Female";
        }
        
        int selectedRow = jTable1.getSelectedRow();
        language = sb.toString();
        
        Object[] rowData = new Object[] {jTextField1.getText(), jTextField2.getText(), jTextField3.getText(), jComboBox1.getSelectedItem(), radioB, language, date};
        
        if (selectedRow != -1) {
            editingRow = selectedRow;
            
            model.setValueAt(jTextField1.getText(), editingRow, 0);
            model.setValueAt(jTextField2.getText(), editingRow, 1);
            model.setValueAt(jTextField3.getText(), editingRow, 2);
            model.setValueAt(jComboBox1.getSelectedItem(), editingRow, 3);
            model.setValueAt(radioB, editingRow, 4);
            model.setValueAt(language, editingRow, 5);
            model.setValueAt(date, editingRow, 6);
            editingRow = -1;
            
            JOptionPane.showMessageDialog(this, "Info updated.", "Info update", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(this, "Please select a row first.");
        }
        clearFormFields();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
            printing print = new printing();
            String radioB = "";
            String language;
            String date = "";
            Date selectedDate = jDateChooser1.getDate();
            StringBuilder sb = new StringBuilder();
            JCheckBox[] check = {jCheckBox1, jCheckBox2, jCheckBox3};
        
            for (JCheckBox jcheckbox : check) {
                if (jcheckbox.isSelected()) {
                    sb.append(jcheckbox.getText()).append("\n");
                }
            }
            
            language = sb.toString();
            
            if (jRadioButton1.isSelected()) {
                radioB = "Male";
            }
            else if (jRadioButton2.isSelected()) {
                radioB = "Female";
            }
            
            if (selectedDate.equals(null)) {
                selectedDate = null;
            }
            else {
                SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
                String formattedDate = sdf.format(selectedDate);
                date = formattedDate;
            }
            
            print.jTextField1.setText(jTextField1.getText());
            print.jTextField2.setText(jTextField2.getText());
            print.jTextField3.setText(jTextField3.getText());
            print.jTextField4.setText(jComboBox1.getSelectedItem().toString());
            print.jTextField5.setText(radioB);
            print.jTextField6.setText(language);
            print.jTextField7.setText(date);
            print.setVisible(true);
    }//GEN-LAST:event_printButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        model = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            try {
                Object firstname = model.getValueAt(selectedRow, 0);
                jTextField1.setText(firstname != null ? firstname.toString() : "");
                Object middlename = model.getValueAt(selectedRow, 1);
                jTextField2.setText(middlename != null ? middlename.toString() : "");
                Object lastname = model.getValueAt(selectedRow, 2);
                jTextField3.setText(lastname != null ? lastname.toString(): "");
                String gender = model.getValueAt(selectedRow, 4) != null ? model.getValueAt(selectedRow, 4).toString() : "";
                if (gender.equalsIgnoreCase("Male")) {
                    jRadioButton1.setSelected(true);
                }
                else if (gender.equalsIgnoreCase("Female")) {
                    jRadioButton2.setSelected(true);
                }
                String age = model.getValueAt(selectedRow, 3) != null ? model.getValueAt(selectedRow, 3).toString() : "";
                jComboBox1.setSelectedItem(age);
                String language = model.getValueAt(selectedRow, 5) != null ? model.getValueAt(selectedRow, 5).toString() : "";
                jCheckBox1.setSelected(language.contains("English"));
                jCheckBox2.setSelected(language.contains("Bisaya"));
                jCheckBox3.setSelected(language.contains("Tagalog"));
                String datedate = model.getValueAt(selectedRow, 6) != null ? model.getValueAt(selectedRow, 6).toString() : "";
                Date deyt = new SimpleDateFormat("MM/dd/yyyy").parse(datedate);
                jDateChooser1.setDate(deyt);
                
            }
            catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error loading info.", "Updating info error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Select a row first.");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton printButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
